/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseworkpizza;

import java.awt.Color;

/**
 *
 * @author chloe
 */
public class HomePage extends javax.swing.JFrame {
    private Order theOrder;
    private NewPizzaPage pizzaGui;
    private EditDeletePizzaPage editGui;
    /**
     * Creates new form Gui2
     */
    
    public HomePage(){
        initComponents();
        theOrder = new Order();
        orderArea.setText(theOrder.showOrder());
        totalText.setText("£ " + theOrder.getTotalOrderPrice()); 
        this.getContentPane().setBackground(Color.white);
    }
    
    /**
     * Create a function that can be called when the order text needs to be 
     * refreshed
     */
    public void orderNeedsUpdate(){
        orderArea.setText(theOrder.showOrder());
        totalText.setText("£ " + theOrder.getTotalOrderPrice());  
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPizzaBtn = new javax.swing.JButton();
        editDeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 800));

        newPizzaBtn.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        newPizzaBtn.setLabel("New Pizza");
        newPizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPizzaBtnActionPerformed(evt);
            }
        });

        editDeleteBtn.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        editDeleteBtn.setLabel("Edit or Delete pizza");
        editDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeleteBtnActionPerformed(evt);
            }
        });

        orderArea.setBackground(new java.awt.Color(176, 224, 230));
        orderArea.setColumns(20);
        orderArea.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        orderArea.setRows(5);
        jScrollPane1.setViewportView(orderArea);

        jLabel1.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel1.setText("Overal Total :");

        totalText.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        totalText.setText("Total");
        totalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextActionPerformed(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        closeBtn.setLabel("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeBtn)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newPizzaBtn)
                                .addGap(51, 51, 51)
                                .addComponent(editDeleteBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(131, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPizzaBtn)
                    .addComponent(editDeleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPizzaBtnActionPerformed
        // TODO add your handling code here:
        //create and open a newPizzaPage
        pizzaGui = new NewPizzaPage(theOrder, this);
        pizzaGui.setVisible(true);
       
    }//GEN-LAST:event_newPizzaBtnActionPerformed

    private void totalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void editDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeleteBtnActionPerformed
        // TODO add your handling code here:
        if(theOrder.getNumberOfPizzas() > 0){
        editGui = new EditDeletePizzaPage(theOrder, this);
        editGui.setVisible(true);
        }
    }//GEN-LAST:event_editDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editDeleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newPizzaBtn;
    private javax.swing.JTextArea orderArea;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
