/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseworkpizza;
import java.awt.Color;
/**
 *
 * @author chloe
 */
public class NewPizzaPage extends javax.swing.JFrame {
    private Pizza myPizza;
    private Order theOrder;
    private HomePage homeP;
    
    public NewPizzaPage() {
        initComponents();
    }
    public NewPizzaPage(Order order, HomePage homeP) {
        initComponents();
        theOrder = order;
        this.homeP = homeP;
        myPizza = new Pizza(size.Small, crust.Thin, sauce.Tomato, topping1.None, topping2.None );
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
        this.getContentPane().setBackground(Color.white);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeCmb = new javax.swing.JComboBox<>();
        sauceCmb = new javax.swing.JComboBox<>();
        crustCmb = new javax.swing.JComboBox<>();
        topping1Cmb = new javax.swing.JComboBox<>();
        topping2Cmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addPizzaBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderPriceArea = new javax.swing.JTextArea();

        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(176, 224, 230));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(700, 1000));

        sizeCmb.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        sizeCmb.setModel(new javax.swing.DefaultComboBoxModel<size>(size.values()));
        sizeCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeCmbActionPerformed(evt);
            }
        });

        sauceCmb.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        sauceCmb.setModel(new javax.swing.DefaultComboBoxModel<sauce>(sauce.values()));
        sauceCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauceCmbActionPerformed(evt);
            }
        });

        crustCmb.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        crustCmb.setModel(new javax.swing.DefaultComboBoxModel<crust>(crust.values()));
        crustCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crustCmbActionPerformed(evt);
            }
        });

        topping1Cmb.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        topping1Cmb.setModel(new javax.swing.DefaultComboBoxModel<topping1>(topping1.values()));
        topping1Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topping1CmbActionPerformed(evt);
            }
        });

        topping2Cmb.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        topping2Cmb.setModel(new javax.swing.DefaultComboBoxModel<topping2>(topping2.values()));
        topping2Cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topping2CmbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel1.setText("Size");

        jLabel2.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel2.setText("Sauce");

        jLabel3.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel3.setText("Crust");

        jLabel4.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel4.setText("Topping1");

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        jLabel5.setText("Topping2");

        addPizzaBtn.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        addPizzaBtn.setText("Add to order");
        addPizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPizzaBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        orderPriceArea.setBackground(new java.awt.Color(176, 224, 230));
        orderPriceArea.setColumns(20);
        orderPriceArea.setFont(new java.awt.Font("AR BONNIE", 0, 18)); // NOI18N
        orderPriceArea.setRows(5);
        jScrollPane1.setViewportView(orderPriceArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sizeCmb, 0, 85, Short.MAX_VALUE)
                            .addComponent(sauceCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crustCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping1Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping2Cmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addGap(75, 75, 75)
                        .addComponent(addPizzaBtn)
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sauceCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crustCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping1Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping2Cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPizzaBtn)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sizeCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeCmbActionPerformed
        // TODO add your handling code here:
        myPizza.setSize((size)sizeCmb.getSelectedItem());
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
        
    }//GEN-LAST:event_sizeCmbActionPerformed

    private void sauceCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauceCmbActionPerformed
        // TODO add your handling code here:
        myPizza.setSauce((sauce)sauceCmb.getSelectedItem());
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
    }//GEN-LAST:event_sauceCmbActionPerformed

    private void crustCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crustCmbActionPerformed
        myPizza.setCrust((crust)crustCmb.getSelectedItem());
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
    }//GEN-LAST:event_crustCmbActionPerformed

    private void topping1CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topping1CmbActionPerformed
        myPizza.setTopping1((topping1)topping1Cmb.getSelectedItem());
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
    }//GEN-LAST:event_topping1CmbActionPerformed

    private void topping2CmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topping2CmbActionPerformed
        myPizza.setTopping2((topping2)topping2Cmb.getSelectedItem());
        orderPriceArea.setText(myPizza.getPizzaInfo(myPizza));
    }//GEN-LAST:event_topping2CmbActionPerformed

    private void addPizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPizzaBtnActionPerformed
        theOrder.addPizza(myPizza);
        homeP.orderNeedsUpdate();
        this.setVisible(false);
    
        
    }//GEN-LAST:event_addPizzaBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPizzaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPizzaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPizzaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPizzaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPizzaPage().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPizzaBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<crust> crustCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea orderPriceArea;
    private javax.swing.JComboBox<sauce> sauceCmb;
    private javax.swing.JComboBox<size> sizeCmb;
    private javax.swing.JComboBox<topping1> topping1Cmb;
    private javax.swing.JComboBox<topping2> topping2Cmb;
    // End of variables declaration//GEN-END:variables
}
